name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build specification 
    runs-on:  ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    strategy:
      fail-fast: false

    steps:
      - name: set up git repository
        uses: actions/checkout@v3
        
      - name: set up build
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: set up neutralino
        run: |
          sudo npm install -g @neutralinojs/neu && neu create app && mv app/bin bin && rm -rf app

      - name: install dependencies
        run: |
          cd react-src && npm install && cd ..

      - name: build react
        run: |
          cd react-src && npm run build && cd ..

      - name: build neutralino
        run: |
          ls && neu build --release && ls dist/ProgGame

      - name: upload binaries to artifactory
        uses: actions/upload-artifact@v3
        with:
          name: ProgGame
          path: |
            ./dist/ProgGame
            ./manuals/User_Manual-Programming_Game.pdf
            ./README.md
            ./LICENSE
          if-no-files-found: error
